# Generated by Django 5.0.2 on 2024-02-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_google_calendar_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_calendar_credentials',
        ),
        migrations.AddField(
            model_name='user',
            name='google_calendar_credentials_path',
            field=models.CharField(default='', max_length=300),
        ),
    ]
