# Generated by Django 5.0.2 on 2024-02-21 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_usertoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
